### ISSUE TITLE
Introduce `YuzuMember`

### ISSUE THREAD

**Issue by rotanov** [klenin/Yuzu#17]
Remove `YuzuRequired` and `YuzuOptional`.
Add `required` parameter to `YuzuMember`.
With default value set to `false`.

**Comment by klenin** [comment]
Note that `YuzuRequired`  and `YuzuOptional` retain their previous meaning,
and new `YuzuMember` means `YuzuOptional` + `YuzuDefault(new ThisType().ThisField)`
