### ISSUE TITLE
Discuss conditions when to deserialize INTO fields.

### ISSUE THREAD

**Issue by rotanov** [klenin/Yuzu#42]
Currently the condition is IIRC "if there's a private setter".
Forgetting to place the private setter and having e.g. custom container field with state dependent on owner will lead to this state being not initialized when rewriting the field.
This error is very hard to trace.
I think to deserialize INTO when field is not null would be wrong condition. May be some reasonable defaults and yuzu attribute for customization of this behaviour.

**Comment by klenin** [comment]
Did you see `YuzuMerge`?

**Comment by rotanov** [comment]
Briefly. Didn't track when it appeared.
Will look into it.
