### ISSUE TITLE
Properly fill Meta.cache

### ISSUE THREAD

**Issue by rotanov** [klenin/Yuzu#43]
Meta.cache is not filled properly when we use new (De)Serializer each time. Each new (De)Serializer has new reference to CommonOptions which leads to new entry in Meta.cache with same meaning.
Could be solved by changing CommonOptions to struct and introducing static CommonOptions Default.

**Comment by klenin** [comment]
Added `CommonOptions.Default`.
I am hesitant to use it, however, since it may lead to surprises for unsuspecting application developer.
Perhaps add parameter to (de)serializer constructors instead?

**Comment by rotanov** [comment]
> Perhaps add parameter to (de)serializer constructors instead?

What parameter? `bool useDefaultOptions` or add `CommonOptions options` argument to constructor?

Not using CommonOptions.Default in Yuzu will too lead to surprises for unsuspecting application developer (See OP post)
I suggest using `CommonOptions.Default` instead of `new CommonOptions()` in yuzu. (everywhere but CommonOptions.Default initializer)

It would be great if we could force user to provide CommonOptions class instance every time they want to change some field of options. Without making CommonOptions a `struct`.

**Comment by rotanov** [comment]
Implement GetHashCode() for CommonOptions.
Leave Options = new CommonOptions where it is as it is.
