### ISSUE TITLE
(De)serializing while (de)serializing leads to inconsistent behaviour

### ISSUE THREAD

**Issue by rotanov** [klenin/Yuzu#44]
This one needs more research. The details will probably follow. We'll use new one each time for now.

**Comment by klenin** [comment]
Do you mean calling the same deserializer from multiple threads or resursively, from `AfterDeserialization`?

**Comment by rotanov** [comment]
Recursively, but other way. When deserializing external scenes.

**Comment by rotanov** [comment]
I was wrong: there's no recursion, but some bugs are still present. Will research.
