### ISSUE TITLE
Serialize entire type with single attribute.

### ISSUE THREAD

**Issue by NoiseDoll** [klenin/Yuzu#65]
It would be nice time saver, if I have single attribute to mark every field/property of the type to be serialized.

For example:
```
[YuzuSerializable]
public class MyType
{
  public int Property1 { get; set; }
  public int Property2 { get; set; }
  ...
  public int Property99999 { get; set; }
}
```

Also we may add attribute parameter to define scope to "only properties" or "properties + fields"

**Comment by klenin** [comment]
@NoiseDoll Note that actual implementation would also involve choosing optionality level for items.

**Comment by NoiseDoll** [comment]
```
[YuzuAll(typeof(YuzuRequired), YuzuMemberKind.Property)]
```
