### ISSUE TITLE
new YuzuDontSerialize attribute

### ISSUE THREAD

**Issue by rotanov** [klenin/Yuzu#69]
Create new attribute `YuzuDontSerialize`. When a class is marked with `YuzuDontSerialize`, instances of this class shouldn't be serialized when they are a part of collection (e.g. key or value of dictionary, or element of list). When a field (of type marked with `YuzuDontSerialize`) is marked for serialization (e.g. with `YuzuMember`) `null` should be serialized.

Also consider extending `YuzuSerializeIf` to work with types and then implementing `YuzuDontSerialize` as `YuzuSerializeIf(false)` (not literally since it accepts a method's name, just expressing an idea).

**Comment by klenin** [comment]
Upon further deliberation. implemented `YuzuSerializeItemIf` as a method attribute inside collections.
This allows arbitrary runtime conditions, and avoids slowdown when not using this attribute.
