### ISSUE TITLE
default values

### ISSUE THREAD

**Issue by rotanov** [klenin/Yuzu#7]
We don't want to ever serialize any default values. E.g. Ctrl+Shift+F `"null"` Default here stands for https://msdn.microsoft.com/en-us/library/83fhsxwc.aspx but custom default values would be very nice to have and treat the same. E.g. don't serialize 

```
    [YuzuDefault(DefaultPresener.Instance)]
    Node.Presenter = DefaultPresenter.Instance
```

Or something like that. Also no idea if empty (not null) lists, dictionaries should be treated as default.

**Comment by klenin** [comment]
This already kind-of-works, see `TestDefault`

**Comment by rotanov** [comment]
Add YuzuDefault attribute without parameters: if at least on such attribute exists create class instance using default constructor. Take default values from this instance.

**Comment by rotanov** [comment]
Treat empty list and null as distinct.

**Comment by klenin** [comment]
New `YuzuMember` attribute behaves like this, except for empty containers. Extracted that as issue #40
