### ISSUE TITLE
Bug which cause field skipping if one was added

### ISSUE THREAD

**Issue by NoiseDoll** [klenin/Yuzu#70]
1. Create class:
```
class Data
{
	[YuzuMember]
	public int StarterPackOfferEndTime;
	[YuzuMember]
	public bool StartGoldInitialized;
}
```
2. Serialize it binary.
3. Add field:
```
[YuzuMember]
public bool StarterPackOffered;
```
4. Deserialize it.
5. Observe that all field became "unknown" and values are not applied.

**Comment by klenin** [comment]
In principle, issue is fixed by a98d4c6491594173b1a0b7e4ce906262b4c7a9c2.
For compatibility, see e608caebf3113e46a0f28d319a164c7c0fd4ddc0
